### PR TITLE
Plot method for `data_tabulate`

### LINKED ISSUE #289: Plot method for `data_tabulate()`?
Asked in easystats/datawizard#419 

It would be nice to have a plot method to do this:

``` r
library(ggplot2)
library(datawizard)

# Data Tabulate

## Desired input
dt <- data_tabulate(mpg, select = c("cyl", "drv"))
### Option 1: plot(dt)
### Option 2: data_tabulate(mpg, select = c("cyl", "drv"), plot = TRUE)

## Desired output
mpg |> 
  data_select(select = c("cyl", "drv")) |> 
  data_to_long() |> 
  ggplot(aes(x = value)) +
  facet_wrap(~name, scales = "free") +
  geom_bar()
```

<sup>Created on 2023-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by etiennebacher**
Close #289 

Minimal working version so far (no docs, etc.). It is such a short step to convert the table into a plot that I think we should restrict the number of args to a minimum here. Otherwise it will just be quicker for the users to make a fancy plot by themselves than go through all possible args (e.g the docs of [`sjPlot::plot_freq()`](https://strengejacke.github.io/sjPlot/reference/plot_frq.html) are a bit overwhelming 😅). I have two "important" args in mind for now:

* keep or remove NA? if we keep them we show raw counts and percentage, otherwise only the valid ones
* show or hide counts and percentage on top of bars?

@jmgirard what do you think? 

``` r
library(see)
library(datawizard)
library(patchwork)

x <- data_tabulate(mtcars, select = "cyl")
plot(x)
#> [[1]]
```

``` r

x <- data_tabulate(mtcars, select = c("cyl", "gear"))
my_plots <- plot(x)
wrap_plots(my_plots)
```

### CODE REVIEW

**Comment by etiennebacher** [comment]
@bwiernik did you have something like this in mind? Default is to add error bars (I just took the code from [`sjPlot::plot_frq()`](https://github.com/strengejacke/sjPlot/blob/HEAD/R/plot_frq.R#L344))

``` r
library(see)
library(datawizard)
library(patchwork)

x <- data_tabulate(mtcars, select = "cyl")

plot(x, remove_na = TRUE)
#> [[1]]
```



``` r

plot(x, remove_na = TRUE, error_bar = FALSE)
#> [[1]]
```



<sup>Created on 2023-06-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment]
Remaining tests failures are not caused by this PR, they are also on `main`

**Comment by strengejacke** [comment]
I think this can be merged?

**Comment by bwiernik** [comment]
okay, I made those tweaks. The major one is to use the Wilson CI for proportions rather than the normal approximation -- this avoids getting CI bounds that escape [0, 1] or intervals collapsing to nothing at p = 0 or 1

**Review by bwiernik — APPROVED** [review]

**Comment by bwiernik** [comment]
@IndrajeetPatil do you know why the R-CMD-check-strict on ubuntu is taking forever to load all of the dependencies?

**Comment by strengejacke** [comment]
The automated checks for the _see_ package are a pain, because there are a lot of minor issues, which yield an error (on purpose), but which are difficult to iron out in order to have a "clean basis" for tests.

**Comment by bwiernik** [comment]
That looks like it

**Pull request merged**
