### PR TITLE
Update pp check plot formatting

### PR DESCRIPTION
**Pull request by bwiernik**

### CODE REVIEW

**Comment by bwiernik** [comment]
image

**Comment by strengejacke** [comment]
Nice!

**Review by strengejacke — APPROVED** [review]

**Comment by bwiernik** [comment]
@strengejacke Could you help me get the package versions to work for the tests ?

**Comment by strengejacke** [comment]
I updated the DESCRIPTION file and used more current version numbers, but it should have been enough to add _insight_ to remotes. Let's see...

**Comment by strengejacke** [comment]
@bwiernik @IndrajeetPatil @DominiqueMakowski @mattansb I think a very common question is how to interprete these plots. We already have some more details in the docs, but probably we should provide some guidelines about the meaning of these plots in the docs:

https://easystats.github.io/performance/reference/check_model.html

**Comment by strengejacke** [comment]
Great, you can merge, if you like - unless you want to do more additions here.

**Pull request merged**
