### PR TITLE
Harmonize API

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
cf. https://github.com/easystats/easystats/issues/434

- Rename args to follow `color_*` pattern

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Can change for `alpha_rope`, it is aligned with the mental process of "I want to change the alpha *of* the rope"

**Comment by strengejacke** [comment]
So we (roughly) have the pattern `aes_geom` / `aes_element`...

**Comment by bwiernik** [comment]
One potential consideration is that ggplot2 names these sorts or arguments/aesthetics like: `*.color` 

https://github.com/tidyverse/ggplot2/blob/main/R/geom-boxplot.R

We don't use `.` in argument names ever, so I don't think we should use the "full" ggplot2 naming scheme. Given that, I don't think it makes much difference whether we match the part-first order of names ggplot2 uses vs the aesthetic-first order used in this PR. Personally, I like aesthetic-first better and think we should use it. Just wanted to flag that it is a divergence from how ggplot2 and some extension packages name their arguments.

**Comment by strengejacke** [comment]
I don't think we cover this case here in our coding style guidelines: https://easystats.github.io/easystats/articles/conventions.html

**Comment by strengejacke** [comment]
What about the alphas?

``` r
library(easystats)
easystats_args <- NULL
for (pkg in easystats::easystats_packages()) {
  fns <- ls(paste0("package:", pkg))
  rds_filepath <- file.path(find.package(pkg), "NAMESPACE")
  
  all_fns <- tryCatch(
    as.data.frame(read.table(rds_filepath)),
    error = function(e){
      NULL
    }
  )
  if (!is.null(all_fns)) {
    names(all_fns) <- "func"
    all_fns <- data_filter(all_fns, startsWith(all_fns$func, "S3method("))
    fn <- gsub("S3method\\((.*)\\)", "\\1", all_fns$func)
    fn <- gsub(",", ".", fn, fixed = TRUE)
    
    all_args <- NULL
    for (i in fn) {
      all_args <- c(all_args, formalArgs(getFromNamespace(i, pkg)))
    }
    
    easystats_args <- c(easystats_args, sort(unique(all_args)))
  }
}

grep("alpha", sort(unique(easystats_args)), value = TRUE)
#> [1] "alpha"            "dispersion_alpha" "dot_alpha"        "line_alpha"      
#> [5] "posteriors_alpha" "priors_alpha"     "rope_alpha"       "si_alpha"
```

<sup>Created on 2024-11-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by bwiernik** [comment]
alpha should come first like other aesthetics

**Comment by bwiernik** [comment]
(Those are all plotting parameters and not alpha as in significance right? I think we use "level" for the latter everywhere)

**Comment by bwiernik** [comment]
> I don't think we cover this case here in our coding style guidelines: https://easystats.github.io/easystats/articles/conventions.html

Let's add that to ensure consistency going forward

**Comment by strengejacke** [comment]
> (Those are all plotting parameters and not alpha as in significance right? I think we use "level" for the latter everywhere)

Yes, I think so.

**Comment by strengejacke** [comment]
``` r
library(easystats)
#> # Attaching packages: easystats 0.7.3.2
#> ✔ bayestestR  0.15.0.2    ✔ correlation 0.8.6    
#> ✔ datawizard  0.13.0.12   ✔ effectsize  0.8.9    
#> ✔ insight     0.99.0.15   ✔ modelbased  0.8.9    
#> ✔ performance 0.12.4.5    ✔ parameters  0.23.0.11
#> ✔ report      0.5.9       ✔ see         0.9.0.9
easystats_args <- NULL
for (pkg in easystats::easystats_packages()) {
  fns <- ls(paste0("package:", pkg))
  rds_filepath <- file.path(find.package(pkg), "NAMESPACE")
  
  all_fns <- tryCatch(
    as.data.frame(read.table(rds_filepath)),
    error = function(e){
      NULL
    }
  )
  if (!is.null(all_fns)) {
    names(all_fns) <- "func"
    all_fns <- data_filter(all_fns, startsWith(all_fns$func, "S3method("))
    fn <- gsub("S3method\\((.*)\\)", "\\1", all_fns$func)
    fn <- gsub(",", ".", fn, fixed = TRUE)
    
    all_args <- NULL
    for (i in fn) {
      fun_args <- formalArgs(getFromNamespace(i, pkg))
      all_args <- rbind(
        all_args,
        data.frame(args = fun_args, fun = i, pkg = pkg)
      )
    }
    easystats_args <- rbind(easystats_args, all_args)
  }
}

easystats_args[grepl("alpha", easystats_args$args, fixed = TRUE), ] |> export_table()
#> args             |                               fun | pkg
#> ----------------------------------------------------------
#> rope_alpha       |   plot.see_bayesfactor_parameters | see
#> rope_alpha       | plot.see_bayesfactor_savagedickey | see
#> alpha            |          plot.see_check_normality | see
#> dot_alpha        |          plot.see_check_normality | see
#> dot_alpha        |           plot.see_check_outliers | see
#> alpha            |          plot.see_check_residuals | see
#> dot_alpha        |          plot.see_check_residuals | see
#> rope_alpha       |         plot.see_equivalence_test | see
#> rope_alpha       |      plot.see_equivalence_test_df | see
#> rope_alpha       |      plot.see_equivalence_test_lm | see
#> priors_alpha     |         plot.see_estimate_density | see
#> posteriors_alpha |         plot.see_estimate_density | see
#> priors_alpha     |              plot.see_p_direction | see
#> line_alpha       |               plot.see_p_function | see
#> priors_alpha     |           plot.see_p_significance | see
#> posteriors_alpha |     plot.see_parameters_brms_meta | see
#> rope_alpha       |     plot.see_parameters_brms_meta | see
#> dispersion_alpha |  plot.see_parameters_distribution | see
#> posteriors_alpha |      plot.see_parameters_simulate | see
#> line_alpha       |     plot.see_performance_pp_check | see
#> alpha            |       plot.see_performance_simres | see
#> dot_alpha        |       plot.see_performance_simres | see
#> priors_alpha     |           plot.see_point_estimate | see
#> rope_alpha       |                     plot.see_rope | see
#> si_alpha         |                       plot.see_si | see
#> line_alpha       |    print.see_performance_pp_check | see
```

<sup>Created on 2024-11-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
And we have all the sizes... `base_size` is maybe ok to keep, but what about `font_size`? 

``` r
library(easystats)
easystats_args <- NULL
for (pkg in easystats::easystats_packages()) {
  fns <- ls(paste0("package:", pkg))
  rds_filepath <- file.path(find.package(pkg), "NAMESPACE")
  
  all_fns <- tryCatch(
    as.data.frame(read.table(rds_filepath)),
    error = function(e){
      NULL
    }
  )
  if (!is.null(all_fns)) {
    names(all_fns) <- "func"
    all_fns <- data_filter(all_fns, startsWith(all_fns$func, "S3method("))
    fn <- gsub("S3method\\((.*)\\)", "\\1", all_fns$func)
    fn <- gsub(",", ".", fn, fixed = TRUE)
    
    all_args <- NULL
    for (i in fn) {
      fun_args <- formalArgs(getFromNamespace(i, pkg))
      all_args <- rbind(
        all_args,
        data.frame(args = fun_args, fun = i, pkg = pkg)
      )
    }
    easystats_args <- rbind(easystats_args, all_args)
  }
}

easystats_args[grepl("size", easystats_args$args, fixed = TRUE), ] |>
  data_filter(pkg %in% c("see", "parameters")) |> 
  export_table()
#> args            |                                 fun |        pkg
#> ------------------------------------------------------------------
#> font_size       |          display.compare_parameters | parameters
#> font_size       |        display.parameters_brms_meta | parameters
#> font_size       |            display.parameters_model | parameters
#> font_size       |         display.parameters_simulate | parameters
#> font_size       |       print_html.compare_parameters | parameters
#> font_size       |     print_html.parameters_brms_meta | parameters
#> font_size       |         print_html.parameters_model | parameters
#> font_size       |           print_html.parameters_sem | parameters
#> font_size       |      print_html.parameters_simulate | parameters
#> size_point      |     plot.see_bayesfactor_parameters |        see
#> size_point      |   plot.see_bayesfactor_savagedickey |        see
#> size_line       |           plot.see_binned_residuals |        see
#> size_point      |           plot.see_binned_residuals |        see
#> size_title      |           plot.see_binned_residuals |        see
#> size_axis_title |           plot.see_binned_residuals |        see
#> base_size       |           plot.see_binned_residuals |        see
#> size_point      |         plot.see_check_collinearity |        see
#> size_line       |         plot.see_check_collinearity |        see
#> size_title      |         plot.see_check_collinearity |        see
#> size_axis_title |         plot.see_check_collinearity |        see
#> base_size       |         plot.see_check_collinearity |        see
#> size_point      |                  plot.see_check_dag |        see
#> size_text       |                  plot.see_check_dag |        see
#> size_point      |         plot.see_check_distribution |        see
#> size_point      | plot.see_check_distribution_numeric |        see
#> size_point      |   plot.see_check_heteroscedasticity |        see
#> size_line       |   plot.see_check_heteroscedasticity |        see
#> size_title      |   plot.see_check_heteroscedasticity |        see
#> size_axis_title |   plot.see_check_heteroscedasticity |        see
#> base_size       |   plot.see_check_heteroscedasticity |        see
#> size_line       |            plot.see_check_normality |        see
#> size_point      |            plot.see_check_normality |        see
#> size_title      |            plot.see_check_normality |        see
#> size_axis_title |            plot.see_check_normality |        see
#> base_size       |            plot.see_check_normality |        see
#> size_text       |             plot.see_check_outliers |        see
#> size_line       |             plot.see_check_outliers |        see
#> size_title      |             plot.see_check_outliers |        see
#> size_axis_title |             plot.see_check_outliers |        see
#> base_size       |             plot.see_check_outliers |        see
#> size_line       |             plot.see_check_overdisp |        see
#> size_title      |             plot.see_check_overdisp |        see
#> size_axis_title |             plot.see_check_overdisp |        see
#> base_size       |             plot.see_check_overdisp |        see
#> size_line       |            plot.see_check_residuals |        see
#> size_point      |            plot.see_check_residuals |        see
#> size_title      |            plot.see_check_residuals |        see
#> size_axis_title |            plot.see_check_residuals |        see
#> base_size       |            plot.see_check_residuals |        see
#> size_point      |         plot.see_compare_parameters |        see
#> size_text       |         plot.see_compare_parameters |        see
#> size_line       |        plot.see_compare_performance |        see
#> size_point      |        plot.see_equivalence_test_lm |        see
#> size_line       |           plot.see_estimate_density |        see
#> size_point      |           plot.see_estimate_density |        see
#> size_line       |        plot.see_estimate_density_df |        see
#> size            |                 plot.see_n_clusters |        see
#> size            |                  plot.see_n_factors |        see
#> size_point      |                 plot.see_p_function |        see
#> size_line       |                 plot.see_p_function |        see
#> size_text       |                 plot.see_p_function |        see
#> size_point      |       plot.see_parameters_brms_meta |        see
#> size_line       |       plot.see_parameters_brms_meta |        see
#> size_text       |       plot.see_parameters_brms_meta |        see
#> size_bar        |    plot.see_parameters_distribution |        see
#> size_text       |             plot.see_parameters_efa |        see
#> size            |             plot.see_parameters_efa |        see
#> size_point      |           plot.see_parameters_model |        see
#> size_text       |           plot.see_parameters_model |        see
#> size_text       |             plot.see_parameters_pca |        see
#> size            |             plot.see_parameters_pca |        see
#> size_point      |             plot.see_parameters_sem |        see
#> size_line       |        plot.see_parameters_simulate |        see
#> size_line       |       plot.see_performance_pp_check |        see
#> size_point      |       plot.see_performance_pp_check |        see
#> size_bar        |       plot.see_performance_pp_check |        see
#> size_axis_title |       plot.see_performance_pp_check |        see
#> size_title      |       plot.see_performance_pp_check |        see
#> base_size       |       plot.see_performance_pp_check |        see
#> size_line       |         plot.see_performance_simres |        see
#> size_point      |         plot.see_performance_simres |        see
#> size_title      |         plot.see_performance_simres |        see
#> size_axis_title |         plot.see_performance_simres |        see
#> base_size       |         plot.see_performance_simres |        see
#> size_point      |             plot.see_point_estimate |        see
#> size_text       |             plot.see_point_estimate |        see
#> size_line       |      print.see_performance_pp_check |        see
#> size_point      |      print.see_performance_pp_check |        see
#> size_bar        |      print.see_performance_pp_check |        see
#> size_axis_title |      print.see_performance_pp_check |        see
#> size_title      |      print.see_performance_pp_check |        see
#> base_size       |      print.see_performance_pp_check |        see
```

**Comment by bwiernik** [comment]
size_line we should change to linewidth since that's the correct ggplot2 argument now

**Comment by bwiernik** [comment]
Let's leave font_size

**Comment by strengejacke** [comment]
I think we should change the arguments in `check_model()`, too, to align with the plot-functions?
https://easystats.github.io/performance/reference/check_model.html

**Comment by bwiernik** [comment]
Yep absolutely. Are there other functions that also have plotting arguments?

**Comment by strengejacke** [comment]
I don't think so. It's because check_model does only plotting, you don't need to `plot()` explicitly. that's why you be pass those arguments directly in check_model. Maybe binned_residuals or check_predictions, I'll check

**Review by bwiernik — COMMENTED** [review]
There are a couple of places where we say "color" to refer fill type variables. Should we switch to "fill_" for those? I'm leaning toward no, as we use one color argument to set both fill and color aesthetics in several places

**Comment by strengejacke** [comment]
> There are a couple of places where we say "color" to refer fill type variables. Should we switch to "fill_" for those? I'm leaning toward no, as we use one color argument to set both fill and color aesthetics in several places

I think we don't need to fully adopt the ggplot2 aes names. If it's a color aesthetic, no matter if for points, lines, or ribbons, `color_*` is ok.

**Comment by strengejacke** [comment]
> size_line we should change to linewidth since that's the correct ggplot2 argument now

I'm fine with both, we could also keep `size_*` for anything that changes geom sizes in a certain way

**Comment by IndrajeetPatil** [comment]
Is there anything remaining to be done here? If not, please approve it so that I can merge it. :) 

I am OK with using color instead of fill, at least for now. Let's see if we get any user feedback.

**Review by bwiernik — APPROVED** [review]

**Comment by bwiernik** [comment]
Lgtm

**Pull request merged**
