### PR TITLE
remove internal helpers

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
- is_empty_object not used anywhere
- use datawizard helper

### CODE REVIEW

**Comment by strengejacke** [comment]
do we want to wait with this? else, we cannot submit _see_ within this release cycle.

**Comment by IndrajeetPatil** [comment]
I can do a quick `datawizard` release on Monday. I will also add a few more helpers today and tomorrow and then submit. 

Do you plan to submit the rest of the packages during the next week?

**Comment by strengejacke** [comment]
no, not that early. I think, _correlation_ needs to go first on CRAN.

**Comment by IndrajeetPatil** [comment]
Yeah, then the updates to datawizard will definitely be on CRAN by then. So feel free to merge this.

**Pull request merged**
