### PR TITLE
use .data pronoun from ggplot2 instead of rlang

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by bwiernik** [comment]
*rlang* isn't a problematic dependency in *see* because it is already imported by *ggplot2*

**Comment by IndrajeetPatil** [comment]
Absolutely, but it bothered me that it was unnecessarily declared as a hard dependency. We need it only to the degree that `{ggplot2}` needs it.

**Comment by strengejacke** [comment]
I really don't understand why `aes_string` should be deprecated in the future.

**Comment by bwiernik** [comment]
@strengejacke is this the right issue for your comment?

**Comment by strengejacke** [comment]
it just came to my mind, because the `.data` pronoun was introduced to avoid the "no visible binding for global variable" notes , but instead `aes(x = .data$x)`, _ggplot2_ also allows `aes_string(x = "x")`, which doesn't throw that warning. But I think `aes_string` will be removed in the future... so just commenting on the broader scope here ;-)

**Pull request merged**
