### PR TITLE
Update README.Rmd

### PR DESCRIPTION
**Pull request by pdwaggoner**
rotate X axis labels per discussion for `README` only (at this point...)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
cool :) could you also knit the Rmd so we can update the README alongside? thanks a lot!

**Comment by pdwaggoner** [comment]
I think if you merge the pull request, it will automatically knit and  the `README` will update. Is this what you're asking? I am not sure I have "write access" allowing me to update without submitting pull requests. I could be misunderstanding, though. Apologies if so!

**Comment by DominiqueMakowski** [comment]
No it won't automatically knit unfortunately, we have to update the READMEs, the websites and all manually 😞 So best if you can knit it on your side, and then add another commit from your branch to this PR, and then we can merge it :)

**Comment by strengejacke** [comment]
If you knit the rmd within RStudio, it'll create the md-file, which you can commit directly into this PR.

**Comment by pdwaggoner** [comment]
I see. I just tried, but I have the latest version of R (`3.5.3`), and it says the `see` package isn't available for this latest version... So sorry. Would one of you mind knitting? Or possibly updating the `see` package to interface with the latest release of R? Or if you have another idea, I am happy to do it... This is becoming more complex than I thought originally; apologies for that!

**Comment by DominiqueMakowski** [comment]
That's good, it identifies possible bugs that we can address 😛 

`see` have no particular version restriction tho, I wonder why it errors 🤔

**Comment by pdwaggoner** [comment]
Yeah I was a bit surprised by it as well. Here is what I got:

```{R}
install.packages("see")
## Warning in install.packages :
##  package ‘see’ is not available (for R version 3.5.3)
```

**Comment by DominiqueMakowski** [comment]
oh yes because it's not on CRAN, try installing it from github (see the README)

**Comment by pdwaggoner** [comment]
Ok I got it installed and working except for the last two chunks of code (for `Probability of Direction (pd)` under `BayestestR support`)

Here is the error I got when knitting:

```{R}
## Error in plot.window(...) : need finite 'xlim' values
## In addition: Warning messages:
## 1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
## 2: In min(x) : no non-missing arguments to min; returning Inf
## 3: In max(x) : no non-missing arguments to max; returning -Inf
```

Not sure what to do here...

**Comment by DominiqueMakowski** [comment]
That's *possibly* because of bayestestR version

Basically, we have different versions of a package coexisting, the CRAN version is the "official" one, then there is the github master branch, often a bit more advanced (i.e. might contain updates the CRAN does not yet have), and then we *sometimes* (we *try* to... ^^) have a dev branch, which is a Work in Progress branch. Usually, this dev branch is connected to the master via a PR. You can see examples of such PR in [bayestestR](https://github.com/easystats/bayestestR/pull/67) or [report](https://github.com/easystats/report/pull/15). 

Basically, as it is the beginning of easystats, there are many things that we do in parallel and necessitate to have pretty much all the easystats package updated (usually at dev state). The easiest way to do that is to have github desktop version with a local version of all the packages. These packages should be connected to the dev branch and, when there are updates, you "fetch origin" (i.e. update your local version) of a package, then rebuilt it. 

It sounds tedious (and it is, especially if you're new to it), but in the end it becomes quite automatic and easy. 

Anyway, try updating bayestestR up to the dev version, and see if the code works then ^^

**Comment by pdwaggoner** [comment]
Ok - I think I follow you there. But after trying, I still got the same error. Very strange. Sorry for the troubles! It is likely something on my end, though knitting a simple .Rmd file should be straightforward enough.

**Comment by strengejacke** [comment]
Don't worry, we can help out in such cases (and knit the rmd file), because I won't expect you to already having setup a feasible workflow.

**Comment by DominiqueMakowski** [comment]
I've updated theme and rotation based on your suggestions :)

**Comment by pdwaggoner** [comment]
Many thanks guys - apologies for being unable to figure this one out. Thanks for the added help! Glad it worked out.

**Pull request closed without merging**
