### PR TITLE
Update VIF plot with CIs

### PR DESCRIPTION
**Pull request by bwiernik**
Closes https://github.com/easystats/see/issues/216#issuecomment-1105697962

image

image

### CODE REVIEW

**Comment by strengejacke** [comment]
If VIF is considered as factor, similar to OR or RR, should we have a logarithmic y-scale then? would also make CIs more symmetric.

**Comment by bwiernik** [comment]
I don't have a strong preference for log vs linear scale. 


Not log:
image

Log:
image

**Comment by bwiernik** [comment]
Which do folks think is clearer? With or without a log-transform?

Linear scale:
image

Log scale:
image


Also, what do you think about the revised subtitle?

**Comment by strengejacke** [comment]
The y-position where the blue shaded area starts looks a bit inaccurate for the log-scale, thus I would vote for not-log-scale - unless this bug could be fixed, then I'd probably prefer log scale :-)

**Comment by strengejacke** [comment]
Oh, and subtitle is fine!

**Comment by strengejacke** [comment]
image

**Comment by bwiernik** [comment]
Yeah, that seems to be some sort of ggplot2 bug interacting between transformations and breaks computations. Let's go with a linear scale for now.

**Comment by bwiernik** [comment]
What do you think of this (log10)?

image

image

**Comment by strengejacke** [comment]
Nice! That looks very good!

**Comment by bwiernik** [comment]
@strengejacke Can you check out the branch on windows and see if the ≥ symbol comes through nicely?

**Comment by strengejacke** [comment]
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

image

**Comment by bwiernik** [comment]
Why add .Rproj to .gitignore? It's very useful to have that be part of the clone

**Comment by strengejacke** [comment]
> Why add .Rproj to .gitignore? It's very useful to have that be part of the clone

I have different settings, so we would always overwrite with our own presets? But I don't mind removing it from ignore...

**Comment by strengejacke** [comment]
But I don't think it'll be removed, it will just not be committed anymore...

**Comment by bwiernik** [comment]
The value of the .Rproj file is that it makes us have consistent settings because they are stored in that file.

**Pull request merged**
