### PR TITLE
Fix return class of check_model() patchwork

### PR DESCRIPTION
**Pull request by bwiernik**
Closes https://github.com/easystats/performance/issues/712

### CODE REVIEW

**Review by strengejacke — APPROVED** [review]

**Comment by bwiernik** [comment]
The R CMD Checks look good--not sure about the other workflows

**Comment by bwiernik** [comment]
@strengejacke the issue was that apparently invisible() doesn't also return unless it's the last line of the function and gets the implicit return. I didn't realize that

**Comment by strengejacke** [comment]
> The R CMD Checks look good--not sure about the other workflows

I think you can ignore the other workflows. They error due to warnings which are hard to silence. 
@IndrajeetPatil do you have any ideas how to handle the failing workflows?

**Comment by IndrajeetPatil** [comment]
We just need to fix the new warnings generated by `ggplot2 3.5.0`; I am waiting for `ggplot2 3.5.1`, which would silence some of these warnings.

**Pull request merged**
