### PR TITLE
RC: CRAN 0.9.0

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Need to wait for performance to be updated on CRAN.

**Comment by strengejacke** [comment]
Ah, the examples... I thought the performance update requires the see update 🙈

**Comment by strengejacke** [comment]
_insight_, _datawizard_ and _performance_ updates are on CRAN! :)

**Comment by IndrajeetPatil** [comment]
Awesome, thanks! 😊 

I will resubmit tomorrow.

**Comment by strengejacke** [comment]
If not tooooo late 😬 you may wait for #361

**Comment by strengejacke** [comment]
(else, no big deal - the PR deals with the changes made in https://github.com/easystats/bayestestR/issues/663)

**Comment by strengejacke** [comment]
> If not tooooo late 😬 you may wait for #361

(and #363)

**Review by strengejacke — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
Submitted! 🤞

**Pull request merged**
