### PR TITLE
added show_zero arg to plot.bayestestR_hdi

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by strengejacke** [comment]
I just wanted to suggest "why not call it `show_intercept`", but we have this arg already for the intercept parameter... But maybe we can just call that argument `zero_line`?

**Comment by DominiqueMakowski** [comment]
Initially, I thought about 'mark_zero' or 'vline=0', but looking at the list of args we have others `show_*` so I thought why not show_zero. But I agree, might not be the best... but zero_line sounds a bit weird too 😕

**Comment by strengejacke** [comment]
`intercept_line`.

**Comment by DominiqueMakowski** [comment]
> intercept_line

Not but it would be confusing with the show intercept in which the intercept refers to the intercept parameter of a model, whereas here it's just a line on 0 but it's not really an intercept per se ^^

**Comment by strengejacke** [comment]
> > intercept_line
> 
> Naw but it would be confusing with the show intercept in which the intercept refers to the intercept parameter of a model, whereas here it's just a line on 0 but it's not really an intercept per se ^^

True. So maybe we can stick to `show_zero` for now.

**Pull request merged**
