### PR TITLE
check_homogeneity: demean, subtitle, direct labeling

### PR DESCRIPTION
**Pull request by bwiernik**
Closes https://github.com/easystats/see/issues/146

### CODE REVIEW

**Review by IndrajeetPatil — APPROVED** [review]
Looks good!

**Comment by bwiernik** [comment]
``` r
library(performance)
devtools::load_all(path = "C:/Users/brenton/GitHub/see")
#> i Loading see
model <- lm(len ~ supp + dose, data = ToothGrowth)
result <- check_homogeneity(model)
#> OK: Variances in each of the groups are the same (Bartlett Test, p = 0.226).
plot(result)
```



<sup>Created on 2021-06-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DominiqueMakowski** [comment]
Why have the x axis labels as labels instead of (rotated) x axis 🤔 it seems strange to have the x axis empty... couldn't we also keep colours for other additional  information (I don't know what tho ^^)

**Comment by bwiernik** [comment]
Direct labeling is easier than having to reference back and forth to the axis and distributions. More importantly, x axis labels will frequently overlap. Dodging the axis labels with `guide_axis()` is hard to find a general solution for. Rotated text is generally a bad idea IMO because it's hard to read.

**Pull request merged**
