### PR TITLE
Replace internal reshape by datawizard::reshape_longer

### LINKED ISSUE #185: remove `.reshape_to_long`?
Use [`datawizard::reshape_longer`](https://easystats.github.io/datawizard/reference/data_to_long.html) and remove the internal variant?

https://github.com/easystats/see/blob/ec14dc8fbf63950848d520ea9694fd62bcd08804/R/reshape_to_long.R

### PR DESCRIPTION
**Pull request by etiennebacher**
The tests pass but the coverage on codecov isn't so great so I'm not sure these changes will be important. Apparently, there was a reason for converting factors to characters but no one remembers it (see the issue). 
 
Close #185.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@strengejacke Can this be merged?

**Comment by strengejacke** [comment]
No.

```r
library(easystats)
lm1 <- lm(Sepal.Length ~ Species, data = iris)
lm2 <- lm(Sepal.Length ~ Species + Petal.Length, data = iris)
m1 <- lm(mpg ~ wt, data = mtcars)
m2 <- glm(vs ~ wt + cyl, data = mtcars, family = "binomial")
compare_parameters(lm1, lm2, m1, m2) |> plot()
```

current _see_ version:
image

this PR:
image

**Comment by strengejacke** [comment]
Only the first plot is in line with the text output.

**Comment by strengejacke** [comment]
I suggest closing this PR.

**Comment by IndrajeetPatil** [comment]
Damn; no tests for these plots.

At any rate, it doesn't seem like there is a way to adapt the _datawizard_ version of this function to act like its internal copy in _see_, so we can give up on this pipe dream of removing duplication.

**Pull request closed without merging**
