### PR TITLE
plot.n_factors: Add % of variance to plot

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
Should be non-breaking and work with https://github.com/easystats/parameters/pull/921

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
New plot: image

**Comment by strengejacke** [comment]
So the basic message is that using 4 or more factors does not significantly increase the explained variance?

**Comment by DominiqueMakowski** [comment]
Yes, although variance explained is only used for a subset of methods to determine the optimal number of factors (so it's not the only thing that impact the result of the *n* methods that we test)

 *but* it's quite standard procedure to report it when we do EFA, and it's one of these "intuitive" index. 
And usually I wouldn't be a big fan of dual axis, but because the line is monotonically increasing towards the right, it's also okay IMO to have it on the right-hand axis (it's fairly readable I think?)

**Review by strengejacke — APPROVED** [review]

**Comment by DominiqueMakowski** [comment]
should I merge?

**Comment by IndrajeetPatil** [comment]
> should I merge?

Can you please have a look at the build failures? Workflows that are passing on the default branch are failing here.

**Comment by strengejacke** [comment]
Is this new and probably related to the last changes?

```
✖ Quitting from lines 475-482 [unnamed-chunk-37] (parameters.Rmd)
Caused by error:
! in callr subprocess.
Caused by error:
! replacement has 4 rows, data has 150
Backtrace:
    ▆
 1. ├─base::plot(result)
 2. └─parameters:::plot.cluster_analysis(result)
 3.   ├─base::plot(datawizard::visualisation_recipe(x, ...)) at parameters/R/plot.R:75:3
 4.   ├─datawizard::visualisation_recipe(x, ...) at parameters/R/plot.R:75:3
 5.   └─parameters:::visualisation_recipe.cluster_analysis(x, ...)
 6.     ├─base::`$<-`(`*tmp*`, "Cluster", value = `<chr>`) at parameters/R/cluster_analysis.R:473:3
 7.     └─base::`$<-.data.frame`(`*tmp*`, "Cluster", value = `<chr>`) at parameters/R/cluster_analysis.R:473:3
```

**Comment by strengejacke** [comment]
This error is a mystery to me.

```r
Quitting from lines 284-294 [unnamed-chunk-22] (parameters.Rmd)
Error in `map()`:
ℹ In index: 6.
ℹ With name: vignettes/parameters.Rmd.
Caused by error in `seq_len()`:
! (converted from warning) first element used of 'length.out' argument
Backtrace:
 1. parameters::model_parameters(ma)
 2. parameters:::model_parameters.rma(ma)
      at parameters/R/1_model_parameters.R:301:3
 3. parameters:::.model_parameters_generic(...)
      at parameters/R/methods_metafor.R:76:3
    ...
      at parameters/R/1_model_parameters.R:622:3
 5. parameters:::.format_value_labels(params, model)
      at parameters/R/utils_model_parameters.R:62:3
 6. insight::get_data(model, source = "mf", verbose = FALSE)
      at parameters/R/format_parameters.R:372:5
Execution halted
```

**Pull request merged**
